services:
  api:
    build:
      context: ../backend
      dockerfile: Dockerfile
    image: infra-api
    restart: unless-stopped
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost:8000/health"]
      interval: 15s
      timeout: 5s
      retries: 4
      start_period: 20s

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    image: infra-frontend
    restart: unless-stopped
    ports:
      - "5173:5173"
    depends_on:
      api:
        condition: service_healthy
    healthcheck:
      # use curl (installed in Dockerfile) instead of wget
      test: ["CMD", "curl", "-fsS", "http://localhost:5173/"]
      interval: 15s
      timeout: 5s
      retries: 4
      start_period: 10s
