version: "3.9"
services:
  api:
    build: ../backend
    env_file: ../.env
    ports: ["8000:8000"]
    restart: unless-stopped
  frontend:
    build: ../frontend
    env_file: ../.env
    ports: ["5173:5173"]
    depends_on: [api]
    restart: unless-stopped
