# Docker Compose for Quant Assistant
# - Frontend: Vite (preview server)
# - Backend : FastAPI (Uvicorn)

name: infra

services:
  api:
    build:
      context: ../backend
      dockerfile: Dockerfile
    container_name: infra-api-1
    ports:
      - "8000:8000"
    environment:
      - MOCK_MODE=1
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    container_name: infra-frontend-1
    depends_on:
      api:
        condition: service_healthy
    ports:
      - "5173:5173"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5173"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

