name: CI

on:
  push:
    branches: ["**"]
  pull_request:

jobs:
  api-ui-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # -------- Backend quick import check --------
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Backend deps
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt
          python -c "import fastapi, uvicorn; print('Backend imports OK')"

      # -------- Frontend install & optional build --------
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: frontend/package.json

      # Use npm install (tolerant) instead of npm ci (requires lockfile)
      - name: Frontend install
        working-directory: frontend
        run: |
          npm install --no-audit --no-fund

      # Try a production build, but don't fail the whole CI if it isn't a prod app
      - name: Frontend build (best-effort)
        working-directory: frontend
        run: |
          npm run build || echo "Skipping prod build (dev server app)"

      # -------- Docker smoke build (no push) --------
      - name: Docker meta
        run: docker version

      - name: Build API image
        run: docker build -t qa-api-ci ./backend

      - name: Build Frontend image
        run: docker build -t qa-frontend-ci ./frontend
