name: CI
on:
  push: {branches: ["**"]}
  pull_request:
jobs:
  api-ui-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Backend deps check
        uses: actions/setup-python@v5
        with: { python-version: "3.11" }
      - run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt
          python -c "import fastapi,uvicorn; print('Backend imports OK')"
      - name: Frontend install
        uses: actions/setup-node@v4
        with: { node-version: '20' }
      - run: |
          cd frontend
          npm ci
          npm run build || true  # dev server app; allow success without prod build
      - name: Docker build (no push)
        run: |
          docker build -t qa-api-ci ./backend
          docker build -t qa-frontend-ci ./frontend
