name: CI

on:
  push:
    branches: ["**"]
  pull_request:

jobs:
  build-and-smoke:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # ---------- Backend: install + import smoke ----------
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Backend deps
        working-directory: backend
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Backend import check
        run: |
          python - <<'PY'
          import fastapi, uvicorn
          print("FastAPI & Uvicorn imports OK")
          PY

      # ---------- Frontend: install + build ----------
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: frontend/package-lock.json

      # Use npm install (tolerant) instead of npm ci (requires lockfile match)
      - name: Frontend install
        working-directory: frontend
        run: |
          npm install --no-audit --no-fund

      # Build the Vite app; don't fail CI on warnings
      - name: Frontend build
        env:
          CI: "false"
        working-directory: frontend
        run: |
          npm run build

      # ---------- Upload built frontend as artifact (optional) ----------
      - name: Upload frontend dist
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: frontend-dist
          path: frontend/dist
