name: CI

on:
  push:
    branches: ["**"]
  pull_request:

jobs:
  build-and-smoke:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # --- Backend ---
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Backend deps
        working-directory: backend
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Backend import check
        run: |
          python - <<'PY'
          import fastapi, uvicorn
          print("FastAPI & Uvicorn imports OK")
          PY

      # --- Frontend ---
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          # Use package.json so cache works even if lockfile isn't committed
          cache-dependency-path: frontend/package.json

      - name: Show frontend files (debug)
        run: ls -la frontend

      - name: Frontend install (no lockfile required)
        working-directory: frontend
        run: npm install --no-audit --no-fund

      - name: Frontend build
        env: { CI: "false" }
        working-directory: frontend
        run: npm run build

      - name: Upload build artifact (optional)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: frontend-dist
          path: frontend/dist

