name: Release (Docker Hub)
on:
  push:
    tags: ["v*.*.*"]
jobs:
  release:
    runs-on: ubuntu-latest
    env:
      IMAGE_API: ${{ vars.IMAGE_API }}
      IMAGE_FE: ${{ vars.IMAGE_FE }}
    steps:
      - uses: actions/checkout@v4
      - name: Load image names
        run: |
          if [ -z "${IMAGE_API}" ] || [ -z "${IMAGE_FE}" ]; then
            # fallback to .docker.env if repo vars not set
            source .docker.env
            echo "IMAGE_API=$IMAGE_API" >> $GITHUB_ENV
            echo "IMAGE_FE=$IMAGE_FE" >> $GITHUB_ENV
          fi
      - name: Docker login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Buildx setup
        uses: docker/setup-buildx-action@v3
      - name: Build & push API
        uses: docker/build-push-action@v6
        with:
          context: ./backend
          push: true
          tags: |
            ${{ env.IMAGE_API }}:latest
            ${{ env.IMAGE_API }}:${{ github.ref_name }}
      - name: Build & push Frontend
        uses: docker/build-push-action@v6
        with:
          context: ./frontend
          push: true
          tags: |
            ${{ env.IMAGE_FE }}:latest
            ${{ env.IMAGE_FE }}:${{ github.ref_name }}
